#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
GITROOT="${SCRIPTPATH}"

if [ -s "${GITROOT}/scripts/sys_lib.sh" ]; then
    SCRIPTS="${GITROOT}/scripts"
else
    SCRIPTS="/usr/local/lib/helm/scripts"
fi

source "${SCRIPTS}/sys_lib.sh"

case "$1" in
    "install" | "in" | "i")
        "${SCRIPTS}/sys_install.sh"
        ;;
    "update" | "up" | "u")
        "${SCRIPTS}/sys_update.sh"
        ;;
    "start")
        elevate systemctl start flotilla.service
        ;;
    "status" | "stat")
        elevate systemctl status flotilla.service
        ;;
    "follow" | "f")
        elevate journalctl -f -u flotilla.service
        ;;
    "stop")
        elevate systemctl stop flotilla.service
        ;;
    "ovpn")
        # NOTE: OpenVPN must be running?
        case "$2" in
            "gen")
                elevate docker run -v /opt/flotilla/config/openvpn:/etc/openvpn --log-driver=none \
                    --rm -it kylemanna/openvpn easyrsa build-client-full \
                    "$3" nopass
                elevate docker run -v /opt/flotilla/config/openvpn:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient "$3" > "$3.ovpn"
                ;;
            "get")
                elevate docker run -v /opt/flotilla/config/openvpn:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient "$3" > "$3.ovpn"
                ;;
            "revoke")
                elevate docker run -v /opt/flotilla/config/openvpn:/etc/openvpn --rm kylemanna/openvpn ovpn_revokeclient "$3"
                ;;
            "remove")
                elevate docker run -v /opt/flotilla/config/openvpn:/etc/openvpn --rm kylemanna/openvpn ovpn_revokeclient "$3" remove
                ;;
            *)
                echo "Usage: helm gen <gen | get>"
                ;;
        esac
        ;;
    *)
        echo "Usage: helm <install | update | start | status | follow | stop | ovpn>"
        ;;
esac
