---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]
  - job_name: node
    static_configs:
      - targets: [nodeexporter:9100]
