---
version: "3.7"
  # TODO: qbittorrent with VPN inside of container and search functionality.
  # Traefik
  # Nextcloud
  # Rancher?
  # Gitlab
  # Jenkins
  # Blog
  # Jackett
  ## Sonarr
  ## ...
  # Jellyfin
  # Mayan
  # Email server
  # LibreOffice Online / Collabora
  # PiHole or other DNS
  # Joplin
  # Searx
  # PrivateBin
  # Syncthing?
  # EteSync?
  # Bitwarden?
  # Mining operation?
  # Squid Proxy? Or other proxy
  # IRC
  # TOR Node, hidden service
  # i2p
  # KVM?
services:
  traefik:
    image: traefik
    container_name: traefik
    #privileged: true # Necessary for docker access.
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  watchtower:
    # TODO: Not recommended by LinuxServer.io
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - WATCHTOWER_CLEANUP=true
      #- WATCHTOWER_SCHEDULE='0 0 4 * * *' # Every night at 04:00.
      # TODO: Email notifications (requires SMTP).
      # https://containrrr.github.io/watchtower/notifications/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /opt/flotilla/config/watchtower/config.json:/config.json
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    privileged: true # Necessary for sysctl net settings.
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/flotilla/config/openvpn:/etc/openvpn
    environment:
      - EASYRSA_KEY_SIZE=4096
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    ports:
      - 1194:1194/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - RUN_OPTS="--ProxyConnection=cleanroom:8118"
    volumes:
      - /opt/flotilla/config/jackett:/config
      - /opt/flotilla/data/all/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  cleanroom:
    image: binhex/arch-qbittorrentvpn
    container_name: cleanroom
    privileged: true # Necessary for iptables killswitch.
    cap_add:
      - NET_ADMIN
    env_file:
      - /opt/flotilla/secrets.env
    environment:
      - WEBUI_PORT=8800
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK=000
      - DEBUG=false
      - NAME_SERVERS=128.52.130.209,169.239.202.202,84.200.69.80,84.200.70.40,91.239.100.100,89.233.43.71,37.235.1.174,37.235.1.177,1.1.1.1,1.0.0.1
      - LAN_NETWORK=192.168.0.0/16
      - ENABLE_PRIVOXY=yes
      - VPN_ENABLED=yes
      - VPN_PROV=nordvpn # This is a custom VPN.
    volumes:
      - /opt/flotilla/config/cleanroom:/config
      - /opt/flotilla/data/all/torrents:/torrents
      - /opt/flotilla/data/cleanroom:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8800:8800 # Change the WEBUI_PORT environment variable as well!
      - 8118:8118 # Change the proxy port for Jackett as well!
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK=022
    volumes:
      - /opt/flotilla/config/sonarr:/config
      - /opt/flotilla/data/all/tvshows:/tv
      - /opt/flotilla/data/cleanroom:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK=022
    volumes:
      - /opt/flotilla/config/radarr:/config
      - /opt/flotilla/data/all/movies:/movies
      - /opt/flotilla/data/cleanroom:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK=022
    volumes:
      - /opt/flotilla/config/lidarr:/config
      - /opt/flotilla/data/all/music:/music
      - /opt/flotilla/data/cleanroom:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
      - UMASK_SET=<022> #optional
    volumes:
      - /opt/flotilla/config/jellyfin:/config
      - /opt/flotilla/data/all/tvshows:/data/tvshows
      - /opt/flotilla/data/all/movies:/data/movies
      - /opt/flotilla/data/all/music:/data/music
      - /opt/flotilla/data/all/books:/data/books
      - /opt/flotilla/data/all/photos:/data/photos
      - /opt/flotilla/data/jellyfin/transcode:/transcode #optional
    ports:
      - 8096:8096
      #- 8920:8920 #optional, https
    devices:
      - /dev/dri:/dev/dri #optional, for video HW acceleration
    restart: unless-stopped
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - /opt/flotilla/config/heimdall:/config
    ports:
      - 1080:80
      - 1443:443
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Indianapolis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/flotilla/data/portainer:/data
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
  #rancher:
    #image: rancher/rancher
    #container_name: rancher
    #restart: unless-stopped
    #ports:
      #- 1040:80
  #postgres:
    #image: postgres
    #container_name: postgres
    #environment:
      #- POSTGRES_PASSWORD=pronetochange
    #volumes:
      #- /opt/flotilla/data/postgres:/var/lib/postgres/data
  #letsencrypt:
    #image: linuxserver/letsencrypt
    #container_name: letsencrypt
    #cap_add:
      #- NET_ADMIN
    #environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=America/Indianapolis
      #- URL=maxocull.com
      #- SUBDOMAINS=www,cdn,cloud,alan
      #- VALIDATION=http # DNS? so can use wildcards
      ##- DNSPLUGIN=cloudflare #optional
      ##- DUCKDNSTOKEN=<token> #optional
      #- EMAIL=max.ocull@protonmail.com #optional
      #- DHLEVEL=4096 #optional
      #- ONLY_SUBDOMAINS=false #optional
      ##- EXTRA_DOMAINS=<extradomains> #optional
      #- STAGING=false
    #volumes:
      #- /opt/flotilla/config/letsencrypt:/config
    #ports:
      #- 443:443
    #ports:
      #- 80:80
    #restart: unless-stopped
  #nextcloud:
    #image: linuxserver/nextcloud
    #container_name: nextcloud
    #environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=America/Indianapolis
    #volumes:
      #- /opt/flotilla/config/nextcloud:/config
      #- /opt/flotilla/data/nextcloud:/data
    #ports:
      #- 3443:443
    #restart: unless-stopped
